### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alimoeeny** [u3dreal/molecular-plus#1]
Hello, 
I downloaded the repo as a zip file an added it in Blender using the blender Addon UI,
I'm on windows:
I get:
> Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Ali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\molecular-plus-main\__init__.py", line 43, in register
    from . import properties, ui, operators, creators
  File "C:\Users\Ali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\molecular-plus-main\operators.py", line 7, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecular-plus-main' (C:\Users\Ali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\molecular-plus-main\__init__.py)

I must be missing some dependency or something, right?

**Comment by u3dreal** [comment]
The repo itself does not work .. you need to compile the lib .. or get the release .

[https://github.com/u3dreal/molecular-plus/releases](url)
