### ISSUE TITLE
ImportError: cannot import name 'core' from 'molecular-plus-main' (C:\Users\agrow\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular-plus-main\__init__.py)

### ISSUE THREAD

**Issue by boodahdaloot** [u3dreal/molecular-plus#24]
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\agrow\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular-plus-main\__init__.py", line 41, in register
    from . import properties, ui, operators, creators, addon_prefrences
  File "C:\Users\agrow\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular-plus-main\operators.py", line 8, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecular-plus-main' (C:\Users\agrow\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular-plus-main\__init__.py)

**Comment by JoBilert** [comment]
I get the same error on Blender 4.1  (Windows 11) can anybody tell me hwo to fix it?

**Comment by u3dreal** [comment]
4.1 is not yet supported .but there is a recent build here
[https://github.com/u3dreal/molecular-plus/actions/runs/8673570336](url)
unzip once and then install the addon
