### ISSUE TITLE
not able to install the addon correctly 

### ISSUE THREAD

**Issue by ShubhankarS3d** [u3dreal/molecular-plus#60]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\shubh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecular-plus-main\__init__.py", line 39, in register
    from . import properties, ui, operators, creators, addon_prefrences
  File "C:\Users\shubh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecular-plus-main\operators.py", line 9, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecular-plus-main' (C:\Users\shubh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecular-plus-main\__init__.py)

**Comment by ShubhankarS3d** [comment]
using 4.1.1 blender also tryied it on blender 3.1

**Comment by Lartrax** [comment]
Download the addon from the releases section, not the repo. [Here](https://github.com/u3dreal/molecular-plus/releases)

**Comment by ShubhankarS3d** [comment]
I tried these 311 and 310 neither is working it's showing the same issue

**Comment by ShubhankarS3d** [comment]
No no I'm not unzipping it

**Comment by Lartrax** [comment]
Can you join the discord? https://discord.com/invite/tAwvNEAfA3
So we can talk with less delay.

**Comment by ShubhankarS3d** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\shubh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecularplus\__init__.py", line 39, in register
    from . import properties, ui, operators, creators, addon_prefrences
  File "C:\Users\shubh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecularplus\operators.py", line 9, in <module>
    from . import simulate, core
ImportError: DLL load failed while importing core: The specified module could not be found.

**Comment by u3dreal** [comment]
This will happen if you have the wrong python version 3.10 vs 3.11 or if you have the wrong achitecture mac/linux vs windows or if you just download the repo as zip ( there is no compiled core then ) or if you download a version from github actions wich is zipped two times.

I tested the latest release against window and macos and could not reproduce the issue.

**Comment by thesourcecodes** [comment]
same issue here. I have 2 systems: one with Windows 11: 23H2 (Blender 4.1.1) addon installs without problem. One system with Windows 11: 21H2 (Blender 4.1.1) addon cannot be installed and produces error metioned by OP. The only diffrence between systems is Operation system version. I have deleted Blender and appdata and reinstalled blener 4.1.1 still same issue.

**Comment by u3dreal** [comment]
strange ...

**Comment by u3dreal** [comment]
Would be interesting to check why that happens .... can you pm me on discord ?

**Comment by u3dreal** [comment]
should be solved here
[https://github.com/u3dreal/molecular-plus/releases/tag/v2.17.21](url)
