### ISSUE TITLE
installation problem with blender 4.1

### ISSUE THREAD

**Issue by zodiacxuan01** [u3dreal/molecular-plus#61]
Traceback (most recent call last):
File "C:\Program Files|Blender FoundationlBlender 4.1\4.1\scripts(modulesladdon_utils.py", line 376, in enablemod = importlib.import_module(module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files|Blender FoundationlBlender 4.1\4.1\python\iblimportlib!_init_.py", line 126, in import_modureturn bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib. bootstrap>",line 1204,in _gcd_importFile "<frozen importlib. _bootstrap>",line 1176,in _find_and_load
File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib. bootstrap>",line 1204,in _gcd import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241,in _call_with_frames_removed
File "<frozen importlib. bootstrap>",line 1204, in _gcd_import
File "<frozen importlib. bootstrap>",line 1176,in find and load
File "<frozen importlib. bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'molecular-plus-2'

**Comment by u3dreal** [comment]
I do not know what you have done but "molecular-plus-2" should be "molecular-plus" only ... remove all folders from AppData and reinstall the zip from the release page !

**Comment by zodiacxuan01** [comment]
I tried but still have the same problem . And I also tried version 2.17.42, the error  report is the same.
I find no matter what version I installed , on the add-on introduction menu the version shows as 1.17.21. Is that the root of the problem? I  did use a very old version on the first install.
![Uploading _20240805003608.png…]()
